services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "3002:3002"
    env_file: .env

  hospital-service:
    build: ./backend/hospital-service
    ports:
      - "3001:3001"
    env_file: .env

  queue-service:
    build: ./backend/queue-service
    ports:
      - "3003:3003"
    env_file: .env

  triage-service:
    build: ./backend/triage-service
    ports:
      - "3004:3004"
    env_file: .env

  frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - hospital-service
      - queue-service
      - triage-service
